Add repository type and endpoints. Add pull_requests to Story type.
useshortcut/shortcut-lib pull request #99
Opened 2021-04-10 15:00 UTC by AGluhov

2021-04-11 16:57 UTC, hubjacek requested changes
20

2021-04-11 16:59 UTC, hubjacek reviewed
src/index.ts

2021-04-11 17:00 UTC, hubjacek reviewed
10

2021-04-11 17:00 UTC, hubjacek approved these changes

2021-09-13 18:33 UTC, charpeni approved these changes
Thank you!

2021-09-13 18:33 UTC, charpeni commented on src/types.ts
> +  task_ids: Array<ID>;
Nice catch!

2021-09-13 18:40 UTC, merged